# Site settings
title:       z3r0s
email:       dl2863@nyu.edu 
description: > # this means to ignore newlines until "baseurl:"
 
baseurl:     ""
url:        "http://z3r0s.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: z3r0s
bitbucket_username:
stackoverflow_id:
twitter_username: _z3r0s_
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New email!'
    submit:   'submit'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'


# Build settings
highlighter:  rouge
permalink:    pretty
paginate:     8
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
